export const options = [
    { value: "angular", label: "Angular" },
    { value: "ai", label: "Adobe Illustrator" },
    { value: "apache", label: "Apache" },
    { value: "atom", label: "Atom" },
    { value: "aws", label: "AWS" },
    { value: "azure", label: "Azure" },
    { value: "babel", label: "Babel" },
    { value: "bash", label: "Bash" },
    { value: "bootstrap4", label: "Bootstrap" },
    { value: "c++", label: "C++" },
    { value: "canva", label: "Canva" },
    { value: "chakraui", label: "Chakra UI" },
    { value: "csharp", label: "C#" },
    { value: "css3", label: "CSS" },
    { value: "dart", label: "Dart" },
    { value: "django", label: "Django" },
    { value: "docker", label: "Docker" },
    { value: "figma", label: "Figma" },
    { value: "firebase", label: "Firebase" },
    { value: "flask", label: "Flask" },
    { value: "flutter", label: "Flutter" },
    { value: "gcloud", label: "Google Cloud" },
    { value: "git", label: "Git" },
    { value: "github", label: "GitHub" },
    { value: "gitlab", label: "GitLab" },
    { value: "go", label: "Go" },
    { value: "graphql", label: "GraphQL" },
    { value: "html5", label: "HTML" },
    { value: "id", label: "InDesign" },
    { value: "java", label: "Java" },
    { value: "jquery", label: "jQuery" },
    { value: "js", label: "JavaScript" },
    { value: "kotlin", label: "Kotlin" },
    { value: "kubernetes", label: "Kubernetes" },
    { value: "laravel", label: "Laravel" },
    { value: "linux", label: "Linux" },
    { value: "mariadb", label: "MariaDB" },
    { value: "materialui", label: "Material UI" },
    { value: "mongodb", label: "MongoDB" },
    { value: "mongoose", label: "Mongoose" },
    { value: "mysql", label: "MySQL" },
    { value: "nextjs", label: "Next.js" },
    { value: "nodejs", label: "Node.js" },
    { value: "nuxtjs", label: "Nuxt.js" },
    { value: "openai", label: "OpenAI" },
    { value: "php", label: "PHP" },
    { value: "postgresql", label: "PostgreSQL" },
    { value: "postman", label: "Postman" },
    { value: "ps", label: "Photoshop" },
    { value: "python", label: "Python" },
    { value: "pytorch", label: "PyTorch" },
    { value: "radixui", label: "Radix UI" },
    { value: "reactjs", label: "React" },
    { value: "redis", label: "Redis" },
    { value: "redux", label: "Redux" },
    { value: "reactrouter", label: "React Router" },
    { value: "reactquery", label: "React Query" },
    { value: "rust", label: "Rust" },
    { value: "ruby", label: "Ruby" },
    { value: "sass", label: "Sass" },
    { value: "scala", label: "Scala" },
    { value: "shadcnui", label: "shadcn/ui" },
    { value: "slack", label: "Slack" },
    { value: "spring", label: "Spring" },
    { value: "streamlit", label: "Streamlit" },
    { value: "supabase", label: "Supabase" },
    { value: "sveltejs", label: "Svelte" },
    { value: "swift", label: "Swift" },
    { value: "tailwindcss", label: "Tailwind CSS" },
    { value: "typescript", label: "TypeScript" },
    { value: "ubuntu", label: "Ubuntu" },
    { value: "vim", label: "Vim" },
    { value: "vitejs", label: "Vite" },
    { value: "vscode", label: "VS Code" },
    { value: "vuejs", label: "Vue.js" },
    { value: "wordpress", label: "WordPress" },
    { value: "webpack", label: "Webpack" },
    { value: "yoga", label: "Yoga" },
    { value: "zod", label: "Zod" },
    { value: "sublime", label: "Sublime" },
    { value: "solidity", label: "Solidity" },
    { value: "jira", label: "Jira" },
    { value: "elastic", label: "Elasticsearch" },
    { value: "elixir", label: "Elixir" },
    { value: "electron", label: "Electron" },
    { value: "copilotgithub", label: "GitHub Copilot" },
    { value: "analytics", label: "Analytics" },
  ].sort((a, b) => a.label.localeCompare(b.label));

  export const langOptions = [
    {
      language: "English",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/GB.svg",
    },
    {
      language: "Hindi",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/IN.svg",
    },
    {
      language: "Spanish",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/ES.svg",
    },
    {
      language: "German",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/DK.svg",
    },
    {
      language: "Mandarin",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/CN.svg",
    },
    {
      language: "Arabic",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/SA.svg",
    },
    {
      language: "Polish",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/PL.svg",
    },
    {
      language: "Portugese",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/PT.svg",
    },
    {
      language: "French",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/FR.svg",
    },
    {
      language: "Japanese",
      url: "https://purecatamphetamine.github.io/country-flag-icons/3x2/JP.svg",
    },
  ].sort((a, b) => a.language.localeCompare(b.language));

  export const flag={
    "English":"https://purecatamphetamine.github.io/country-flag-icons/3x2/GB.svg",
    "Hindi":"https://purecatamphetamine.github.io/country-flag-icons/3x2/IN.svg",
    "Japanese":"https://purecatamphetamine.github.io/country-flag-icons/3x2/JP.svg",
    "Spanish":"https://purecatamphetamine.github.io/country-flag-icons/3x2/ES.svg",
    "French":"https://purecatamphetamine.github.io/country-flag-icons/3x2/FR.svg",
    "Portugese":"https://purecatamphetamine.github.io/country-flag-icons/3x2/PT.svg",
    "Arabic":"https://purecatamphetamine.github.io/country-flag-icons/3x2/SA.svg",
    "Mandarin":"https://purecatamphetamine.github.io/country-flag-icons/3x2/CN.svg",
    "German":"https://purecatamphetamine.github.io/country-flag-icons/3x2/DK.svg",
    "Polish":"https://purecatamphetamine.github.io/country-flag-icons/3x2/PL.svg"
  }

  export const projectIcons={
    "Planning": "🖖",
    "In Progress": "🔥",
    "Completed": "✅",
    "Deployed": "🚀",
  };